// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgvpuvjgzjeqhrkpdrel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ndnB1dmpnemplcWhya3BkcmVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5ODY3OTMsImV4cCI6MjA2OTU2Mjc5M30.Lvp0FUYuSWucFWTNO-Q4k1H0pWEAe9aQ2s-WphPbNa4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});